### ISSUE TITLE
Change About text

### ISSUE THREAD

**Issue by Matthew-Mosior** [idris-community/idris2-containers#8]
Should we change the About text so that it matches the README?  Since I think this text is what is pulled in by pack-db.

**Comment by stefan-hoeck** [comment]
Yes, that makes sense. Feel free to come up with a PR.

**Comment by Matthew-Mosior** [comment]
> Yes, that makes sense. Feel free to come up with a PR.

I think this is a GitHub specific feature, its just the text that the repository owner sets up in the top right portion of a repositories main page.

**Comment by stefan-hoeck** [comment]
The text pulled in by the pack collection is the `brief` field in the `.ipkg` file.
